version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password  # Hasło dla root
      MYSQL_DATABASE: app_demo      # Nazwa bazy danych
      MYSQL_USER: root0              # Nazwa użytkownika (jeśli root)
      MYSQL_PASSWORD: password      # Hasło użytkownika
    ports:
      - "3307:3306"  # Mapowanie portów
    volumes:
      - mysql-data:/var/lib/mysql  # Zapewnienie trwałości danych

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: symfony_mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  mysql-data:  # Wolumen przechowujący dane
